project:
  type: website

website:
  title: "ahead-indicators"
  navbar:
    left:
      - href: qmd/index.qmd
        text: Home
      - href: qmd/indicators.qmd
        text: Indicators
      - href: qmd/references.qmd
        text: References

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

